### ISSUE TITLE
HTTP 400: Error in call to API function

### ISSUE THREAD

**Issue by FrankKair** [Jesus/dropbox_api#38]
I'm using this gem to get a link to a folder in my Dropbox, but when I perform the following operation, I get an error.

```ruby
link = @client.get_temporary_link(item_path)
```

Here's the error.

```
/Users/Frank/.gems/gems/dropbox_api-0.1.10/lib/dropbox_api/endpoints/base.rb:36:in `process_response': HTTP 400: Error in call to API function "files/get_temporary_link": request body: path: 'None' expected to be a string, got null (DropboxApi::Errors::HttpError)
	from /Users/Frank/.gems/gems/dropbox_api-0.1.10/lib/dropbox_api/endpoints/base.rb:11:in `perform_request'
	from /Users/Frank/.gems/gems/dropbox_api-0.1.10/lib/dropbox_api/endpoints/files/get_temporary_link.rb:14:in `block in <class:GetTemporaryLink>'
	from /Users/Frank/.gems/gems/dropbox_api-0.1.10/lib/dropbox_api/cli
```

The same happened with other functions, such as `create_shared_link_with_settings`.
What am I missing?

**Comment by FrankKair** [comment]
I just realized I was using a reference out of scope to call these methods.
This should be closed.
The API is working perfectly!
